# Generated by Django 5.0.6 on 2024-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='ean',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
