# Generated by Django 5.0.6 on 2024-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_nomenclature_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
