# Generated by Django 5.0.6 on 2024-08-02 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_nomenclaturestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(django.core.validators.MinValueValidator(0, 'The price must be equal or greater than 0.'))]),
        ),
    ]
